const js = require("@eslint/js");

const nodeGlobals = {
  // Node.js built-ins
  require: "readonly",
  module: "readonly",
  exports: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
  process: "readonly",
  console: "readonly",
  Buffer: "readonly",
  URL: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
};

const browserGlobals = {
  // Browser built-ins
  window: "readonly",
  document: "readonly",
  navigator: "readonly",
  localStorage: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  requestAnimationFrame: "readonly",
  cancelAnimationFrame: "readonly",
  getComputedStyle: "readonly",
  console: "readonly",
  acquireVsCodeApi: "readonly",
  vscode: "readonly",
  // Project-wide webview globals (shared across media/ script tags)
  state: "readonly",
  uiState: "readonly",
  icons: "readonly",
  render: "readonly",
  RECIPES_EMPTY_VALUE: "readonly",
  noticeTimer: "writable",
  hydrateState: "readonly",
  ensureSelectionDefaults: "readonly",
  getSelectedCategory: "readonly",
  setSelectedCategory: "readonly",
  getSelectedCategoryGroups: "readonly",
  getVisibleCommands: "readonly",
  getEditingCommand: "readonly",
  isInFavorites: "readonly",
  persistFavorites: "readonly",
  persistDataThenRender: "readonly",
  persistCommandVariables: "readonly",
  collectVariables: "readonly",
  getMissingVariables: "readonly",
  getEnabledAutoVariableNames: "readonly",
  buildCommandVariablesPayload: "readonly",
  resolveCommandTemplate: "readonly",
  resolveGroupTitle: "readonly",
  selectCommandRow: "readonly",
  scrollToAndHighlight: "readonly",
  escapeHtml: "readonly",
  escapeAttr: "readonly",
  formatDateTime: "readonly",
  timeAgo: "readonly",
  generateEntityId: "readonly",
  getAiModelLabel: "readonly",
  getCachedModels: "readonly",
  setModelsCache: "readonly",
  clearModelsCache: "readonly",
  getCommandGlobalDraft: "readonly",
  getCommandLocalDraft: "readonly",
  getCommandSessionDraft: "readonly",
  getCommandRemember: "readonly",
  syncEditCommandDraftFromDom: "readonly",
  autoResizeTextarea: "readonly",
  highlightTemplateHtml: "readonly",
  highlightResolvedHtml: "readonly",
  updateTemplateHighlight: "readonly",
  updateScopeIndicatorDots: "readonly",
  renderMarkdown: "readonly",
  renderCustomSelect: "readonly",
  bindCustomSelect: "readonly",
  renderToggleSwitch3: "readonly",
  renderActionsCell: "readonly",
  renderAiLoadingOverlay: "readonly",
  renderAiPromptModal: "readonly",
  renderAiProviderSetupModal: "readonly",
  renderAiResultsModal: "readonly",
  renderAiSettingsModal: "readonly",
  renderDeleteConfirmModal: "readonly",
  renderUnfavoriteConfirmModal: "readonly",
  renderFavoriteModal: "readonly",
  renderRunConfirmModal: "readonly",
  renderEditTab: "readonly",
  renderAddCommandTab: "readonly",
  renderCommandsTab: "readonly",
  renderCategoriesTab: "readonly",
  renderFavoritesTab: "readonly",
  renderRecentCommandsTab: "readonly",
  renderVariablesTab: "readonly",
  renderVariableInputModal: "readonly",
  renderEnumManagerModal: "readonly",
  renderDevToolsOverlay: "readonly",
  bindCommandsTabEvents: "readonly",
  bindCommandActionButtons: "readonly",
  bindCategoriesTabEvents: "readonly",
  bindFavoritesTabEvents: "readonly",
  bindRecentTabEvents: "readonly",
  bindVariablesTabEvents: "readonly",
  bindEditTabEvents: "readonly",
  bindAddCommandTabEvents: "readonly",
  bindAiSettingsEvents: "readonly",
  bindAiGenerateEvents: "readonly",
  bindFavoriteModalEvents: "readonly",
  bindEnumManagerEvents: "readonly",
  bindCmdTitleLinks: "readonly",
  bindDevToolsEvents: "readonly",
  showNotice: "readonly",
  showError: "readonly",
  paintNotice: "readonly",
  openAiExplainModal: "readonly",
  handleAiExplainResult: "readonly",
  postAiListModels: "readonly",
  postAiRefreshAllModels: "readonly",
  postAiDeleteKey: "readonly",
  postAiExplain: "readonly",
  runConfirmState: "writable",
  deleteConfirmState: "writable",
  favoriteModalState: "writable",
  unfavoriteConfirmState: "writable",
  categoriesModalState: "writable",
  enumManagerState: "writable",
  variableInputState: "writable",
  aiState: "writable",
  aiExplainState: "writable",
  aiProviderSetupModalState: "writable",
};

module.exports = [
  js.configs.recommended,
  // Node.js files: extension entry point and lib modules
  {
    files: ["extension.js", "lib/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: nodeGlobals,
    },
    rules: {
      "no-unused-vars": "warn",
      // Allow empty catch blocks — intentional silent error handling
      "no-empty": ["error", { allowEmptyCatch: true }],
      // Disable — flags valid initializer patterns (e.g. var x = ""; then reassign in if/else)
      "no-useless-assignment": "off",
    },
  },
  // Browser/WebView files
  {
    files: ["media/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: browserGlobals,
    },
    rules: {
      "no-unused-vars": "off",
      // Allow empty catch blocks — intentional silent error handling (e.g. localStorage access)
      "no-empty": ["error", { allowEmptyCatch: true }],
      // Disable — flags valid initializer patterns (e.g. var heading = ""; then reassign in if/else)
      "no-useless-assignment": "off",
    },
  },
  // Test/Node.js files
  {
    files: ["testing/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: nodeGlobals,
    },
    rules: {
      "no-unused-vars": "warn",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-useless-assignment": "off",
    },
  },
  {
    ignores: ["dist/**", "node_modules/**", ".temp/**"],
  },
];
